### ISSUE TITLE
Spec: should ReadyForSyncExecution module argument be generalized?

### ISSUE THREAD

**Issue by takikawa** [tc39/proposal-defer-import-eval#50]
The `ReadyForSyncExecution(module, seen)` operation in the spec expects that the `module` argument is a Cyclic Module Record, but the operation can be called recursively on the imports, which may be module records of a different type.

I suspect there should be a conditional somewhere in the operation that checks "If module is a Cyclic Module Record then ..."

**Comment by nicolo-ribaudo** [comment]
This has been fixed, now `ReadyForSyncExecution` is only called passing actual Cyclic Module Records to it.
